[package]
name = "whisper_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
biquad = "0.4.2"
bson = "2.11.0"
catppuccin-egui = { version = "5.2.0", default-features = false, features = ["egui28"] }
crossbeam = "0.8.4"
directories = "5.0.1"
eframe = { version = "0.28.1", features = ["persistence"] }
egui = { version = "0.28.1", features = ["persistence", "serde", "deadlock_detection"] }
egui_dock = { version = "0.13.0", features = ["serde"] }
egui_extras = { version = "0.28.1", features = ["svg", "resvg"] }
hound = "3.5.1"
lazy_static = "1.5.0"
maplit = "1.0.2"
nvml-wrapper = "0.10.0"
realfft = "3.3.0"
rfd = "0.14.1"
sdl2 = "0.37.0"
serde = { version = "1.0.204", features = ["derive", "rc"] }
strum = "0.26.3"
symphonia = { version = "0.5.4", features = ["opt-simd", "all-codecs"] }
tokio = { version = "1.39.3", features = ["rt"] }
whisper_realtime = { git = "https://github.com/jordan-clayton/whisper-realtime.git", version = "0.1.0", features = ["serde", "crossbeam", "strum"] }

[target.x86_64-apple-darwin.dependencies]
metal = "0.29.0"

[features]
default = []
_gpu = []
cuda = ["whisper_realtime/cuda", "_gpu"]
coreml = ["whisper_realtime/coreml", "_gpu"]
metal = ["whisper_realtime/metal", "_gpu"]
openblas = ["whisper_realtime/openblas"]
opencl = ["whisper_realtime/opencl"]
hipblas = ["whisper_realtime/hipblas", "_gpu"]
