[package]
# TODO: change name
name = "whisper_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_enum = "0.3.0"
biquad = "0.4.2"
bson = "2.11.0"
catppuccin-egui = { version = "5.2.0", default-features = false, features = ["egui28"] }
crossbeam = "0.8.4"
directories = "5.0.1"
eframe = { version = "0.28.1", features = ["persistence"] }
egui = { version = "0.28.1", features = ["persistence", "serde", "deadlock_detection"] }
egui_dock = { version = "0.13.0", features = ["serde"] }
egui_extras = { version = "0.28.1", features = ["svg"] }
hound = "3.5.1"
lazy_static = "1.5.0"
maplit = "1.0.2"
nvml-wrapper = "0.10.0"
realfft = "3.3.0"
rfd = "0.14.1"
sdl2 = "0.37.0"
serde = { version = "1.0.204", features = ["derive", "rc"] }
strum = "0.26.3"
symphonia = { version = "0.5.4", features = ["opt-simd", "all-codecs"] }
tokio = { version = "1.39.3", features = ["rt"] }
whisper_realtime = { git = "https://github.com/jordan-clayton/whisper-realtime.git", version = "0.1.0", features = ["serde", "crossbeam", "strum"] }
log = "0.4.22"
arboard = "3.4.0"
ron = "0.8.1"

[target.x86_64-apple-darwin.dependencies]
metal = "0.29.0"

[package.metadata.packager]
name = "whisper_gui"
# TODO: change name
product-name = "WhisperGUI"
# TODO: change name
identifier = "com.Jordan.WhisperGUI"
resources = ["Cargo.toml", "src", "README.md"]
# TODO: make icons
icons = ["src/assets/check_fat.svg"]
license-file = "LICENSE.md"
category = "Utility"
version = "0.1.0"
out-dir = "./dist"
copyright = ""
description = ""
long-description = ""

# TODO: add icons
#icons = ["src/assets/app_icon_size.png"]

[package.metadata.packager.deb]
depends = ""
section = "rust"

[package.metadata.packager.macos]
frameworks = ["SDL2"]
minimum-system-version = "10.12"
signing-identity = "TODO"

[package.metadata.packager.windows]
allow-downgrades = "true"

[package.metadata.packager.nsis]
# TODO: ico file.
installer-icon = "src/assets/check_fat.svg"

[features]
default = []
_gpu = []
cuda = ["whisper_realtime/cuda", "_gpu"]
coreml = ["whisper_realtime/coreml", "_gpu"]
metal = ["whisper_realtime/metal", "_gpu"]
openblas = ["whisper_realtime/openblas"]
opencl = ["whisper_realtime/opencl"]
hipblas = ["whisper_realtime/hipblas", "_gpu"]
