# TODO: get rid of this and don't use cargo-packager
name ="ribble"
binaries = ["BINARY"]
product-name ="Ribble"
identifier ="com.Jordan.Ribble"
# TODO: add maintainer field
resources =["Cargo.toml", "src", "README.md"]
icons = ["src/assets/icon.icns",
	 "src/assets/whisper_app_icon_1024x1024@1x.png",
	 "src/assets/whisper_app_icon_512x512@1x.png",
	 "src/assets/whisper_app_icon_256x256@1x.png",
	 "src/assets/whisper_app_icon_128x128@1x.png",
	 "src/assets/whisper_app_icon_64x64@1x.png",
	 "src/assets/whisper_app_icon_32x32@1x.png",
	]
license-file ="LICENSE.md"
category ="Utility"
version ="0.1.1"
out-dir ="./dist"
copyright = "Copyright (c) 2024 - Jordan Clayton"
description = "Audio transcription software"
long-description = "Realtime and static (offline) audio transcription tool driven by OpenAI's Whisper ATS. Includes audio recording tooling, as well as hardware acceleration (if supported)."



[deb]
section = "rust"
depends = ["DEPENDS"]
maintainer = "Jordan Clayton"

[appimage]
libs = ["LIBS"]

[macos]
minimum-system-version ="10.12"
signing-identity = "SIGNING_IDENTITY"

[windows]
allow-downgrades = true

[nsis]
installer-icon ="src/assets/whisper_app_icon.ico"
